import Database from 'better-sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';
import { postgresPool } from '../db/postgres.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const sourcePath = process.env.DB_PATH || path.resolve(__dirname, '../db/wraproll.db');
const apply = process.argv.includes('--apply');

if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required.');
if (!apply) throw new Error('Pass --apply to copy the SQLite database into PostgreSQL.');

const sqlite = new Database(sourcePath, { readonly: true, fileMustExist: true });
const quoteIdentifier = (value) => `"${value.replaceAll('"', '""')}"`;
const tables = sqlite.prepare("SELECT name, sql FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();
const tableNames = new Set(tables.map(({ name }) => name));
const foreignKeys = new Map(tables.map(({ name }) => [
  name,
  sqlite.prepare(`PRAGMA foreign_key_list(${quoteIdentifier(name)})`).all(),
]));

function sortByDependencies() {
  const sorted = [];
  const visited = new Set();
  const visiting = new Set();

  function visit(tableName) {
    if (visited.has(tableName)) return;
    if (visiting.has(tableName)) throw new Error(`Circular foreign key dependency involving ${tableName}.`);
    visiting.add(tableName);
    for (const foreignKey of foreignKeys.get(tableName)) {
      if (tableNames.has(foreignKey.table)) visit(foreignKey.table);
    }
    visiting.delete(tableName);
    visited.add(tableName);
    sorted.push(tableName);
  }

  for (const { name } of tables) visit(name);
  return sorted;
}

function postgresTableSql(table) {
  if (!table.sql) throw new Error(`Missing SQLite schema for table ${table.name}.`);
  return table.sql
    .replace(/^CREATE TABLE(?: IF NOT EXISTS)?\s+(?:"[^"]+"|`[^`]+`|\[[^\]]+\]|[^\s(]+)\s*/i, `CREATE TABLE ${quoteIdentifier(table.name)} `)
    .replace(/\bINTEGER\s+PRIMARY KEY(?:\s+AUTOINCREMENT)?\b/gi, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/\bAUTOINCREMENT\b/gi, '')
    .replace(/\bINTEGER\b/gi, 'BIGINT')
    .replace(/\bREAL\b/gi, 'DOUBLE PRECISION')
    .replace(/\bBLOB\b/gi, 'BYTEA')
    .replace(/datetime\(\s*'now'\s*\)/gi, 'CURRENT_TIMESTAMP::text')
    .replace(/DEFAULT\s+CURRENT_TIMESTAMP\b/gi, 'DEFAULT (CURRENT_TIMESTAMP::text)');
}

async function migrate() {
  if (tables.length === 0) throw new Error(`No SQLite tables found in ${sourcePath}.`);
  const tableOrder = sortByDependencies();
  sqlite.exec('BEGIN');

  const client = await postgresPool.connect();
  try {
    await client.query('BEGIN');
    const existingTables = await client.query("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'");
    if (existingTables.rowCount > 0) {
      throw new Error(`PostgreSQL public schema is not empty (${existingTables.rowCount} tables); refusing to overwrite it.`);
    }

    for (const tableName of tableOrder) {
      const table = tables.find((entry) => entry.name === tableName);
      await client.query(postgresTableSql(table));
    }

    const report = [];
    for (const tableName of tableOrder) {
      const columns = sqlite.prepare(`PRAGMA table_info(${quoteIdentifier(tableName)})`).all().map((column) => column.name);
      const quotedColumns = columns.map(quoteIdentifier).join(', ');
      const rows = sqlite.prepare(`SELECT ${quotedColumns} FROM ${quoteIdentifier(tableName)}`).all();
      const insertBatchSize = Math.max(1, Math.floor(60000 / columns.length));

      for (let offset = 0; offset < rows.length; offset += insertBatchSize) {
        const batch = rows.slice(offset, offset + insertBatchSize);
        const values = [];
        const valueRows = batch.map((row, rowIndex) => {
          const placeholders = columns.map((column, columnIndex) => {
            values.push(row[column]);
            return `$${rowIndex * columns.length + columnIndex + 1}`;
          });
          return `(${placeholders.join(', ')})`;
        });
        await client.query(`INSERT INTO ${quoteIdentifier(tableName)} (${quotedColumns}) VALUES ${valueRows.join(', ')}`, values);
      }

      report.push({ table: tableName, rows: rows.length });
    }

    const indexes = sqlite.prepare("SELECT sql FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL ORDER BY name").all();
    for (const { sql } of indexes) await client.query(sql);

    for (const table of tables) {
      const columns = sqlite.prepare(`PRAGMA table_info(${quoteIdentifier(table.name)})`).all();
      const identityColumn = columns.find((column) => column.pk > 0 && column.type.toUpperCase() === 'INTEGER');
      if (identityColumn) {
        await client.query(
          `SELECT setval(pg_get_serial_sequence($1, $2), GREATEST(COALESCE(MAX(${quoteIdentifier(identityColumn.name)}), 1), 1), COUNT(*) > 0) FROM ${quoteIdentifier(table.name)}`,
          [`public.${table.name}`, identityColumn.name],
        );
      }
    }

    for (const entry of report) {
      const result = await client.query(`SELECT COUNT(*) AS count FROM ${quoteIdentifier(entry.table)}`);
      if (Number(result.rows[0].count) !== entry.rows) {
        throw new Error(`Row count mismatch in ${entry.table}: source ${entry.rows}, PostgreSQL ${result.rows[0].count}.`);
      }
    }

    await client.query('COMMIT');
    console.log(`Migrated ${report.length} tables and ${report.reduce((sum, entry) => sum + entry.rows, 0)} rows from ${sourcePath}.`);
    console.log(JSON.stringify(report, null, 2));
  } catch (error) {
    await client.query('ROLLBACK').catch(() => {});
    throw error;
  } finally {
    client.release();
    sqlite.exec('ROLLBACK');
    sqlite.close();
    await postgresPool.end();
  }
}

migrate().catch((error) => {
  console.error(`SQLite to PostgreSQL migration failed: ${error.message}`);
  process.exitCode = 1;
});